# Get Me
GET http://localhost:8899/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzczMDQ5MDUzLCJleHAiOjE3NzQzNDUwNTN9.XktWD_xZBrvSe81HT6VVIMTHL6X5zbwk_n2sl5IXz2A
###

# Register
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
#  "identity" : "",
 "identity" : "1234567890",
#  "identity" : "someone@ggg.mail",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###


#Login
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "1111111111",
# "identity" : "andy@ggg.mail",
 "password" : "123456"
}
###

#Create new post 
POST http://localhost:8899/api/post HTTP/1.1
content-type: application/json

{
   "message": "sample"
}
###
